afhdecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from ecommerce.views import (
                                index,
                                path_to_nobel_book_2,
                                products,
                                single_product,
                                cart,
                                add_to_cart,
                                remove_from_cart,
                                update_cart,
                                temples_list,

                                create_checkout_session,
                                contact,
                                success,
                                cancel,
                                get_my_ebooks,
                                get_my_testSeries,
                                get_code_testSeries,
                                handler404,
                                handler500,
                                who_we_are,
                                what_we_do,
                                vision_mission,
                                our_team,
                                project_knowledge,
                                project_nutrition,
                                nutrition_food_file,
                                nutritional_file_user,
                                other_books_download_file,
                                other_free_books_user,
                                extra_book_view,
                                extra_books_user,
                                nutrition_game,

                                # 365-quinoa-recipe
                                quinoa_recipes_book,
                                path_to_nobel,
                                path_to_nobel_book,
                                rishis_as_scientist,
                                cues_app_project

                            )


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),

    path('ckeditor/',include('ckeditor_uploader.urls')),

    path('project/365-quinoa-recipes-book/', quinoa_recipes_book, name="quinoa-recipes-book"),
    path('project/path-to-nobel/', path_to_nobel, name="path-to-nobel"),
    path('project/path-to-nobel-book-1st-edition/', path_to_nobel_book, name="path-to-nobel-book"),
    path('project/path-to-nobel-book-2nd-edition/', path_to_nobel_book_2, name="path-to-nobel-book-2"),
    path('project/rishis-as-scientist/', rishis_as_scientist, name="rishis-as-scientist"),
    path('project/108-cues-app-project/', cues_app_project, name="108-cues-app-project"),

    # path('about/who-we-are/', who_we_are, name="who-we-are"),

    path('contact/', contact, name="contact"),    

    path('dashboard/', include(("dashboard.urls",'dashboard'), namespace='dashboard')),


    path('about/who-we-are/', who_we_are, name="who-we-are"),
    path('about/what-we-do/', what_we_do, name="what-we-do"),
    path('about/vision-mission/', vision_mission, name="vision-mission"),
    path('about/our-team/', our_team, name="our-team"),
    path('project/nutrition/', project_nutrition, name="project-nutrition"),
    path('project/knowledge/', project_knowledge, name="project-knowledge"),


    path('items/<category>', products, name="buy-items"),
    path('item/<id>/<slug>', single_product,name="single-item"),

    path('remove-from-cart/<item_id>', remove_from_cart, name="remove-from-cart"),
    path('add-to-cart/', add_to_cart, name="add-to-cart"),
    path('cart/', cart, name="cart"),
    path('update-cart/', update_cart, name="update-cart"),

    path('temples-list/', temples_list, name="temples_list"),


    path('nutrition-food-file/', nutrition_food_file, name="nutrition-food-file"),
    path('nutritional-file-user/', nutritional_file_user, name="nutritional-file-user"),

    path('download-book/', other_books_download_file, name="download-books"),
    path('download-book-user/', other_free_books_user, name="download-book-user"),


    path('at-the-feet-of-mother-india/', extra_book_view, name="at-the-feet-of-mother-india"),
    path('extra-book-user/', extra_books_user, name="extra-book-user"),


    path('checkout', create_checkout_session,name='checkout'),

    path('success/<stripe_id>', success),
    path('cancel/<cart_id>', cancel,name="cancel"),

    path('ebooks/<order_id>', get_my_ebooks,name='my-ebooks'),
    path('test-series/<order_id>', get_my_testSeries,name='my-test-series'),

    path('code-test-series/', get_code_testSeries,name='code-test-series'),

    path('nutrition-game/', nutrition_game,name='nutrition-game'),

    path('_nested_admin/', include('nested_admin.urls')),


]


handler404 = handler404
handler500 = handler500


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from dashboard.views import (
                                analytics,
                                users,
                                orders,
                                dnd_orders,
                                cart_detail_view,
                                view_products,
                                add_products,
                                book_download_users,
                                login,
                                logout
                            )


urlpatterns = [

    path('', analytics, name="analytics"),
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),

    path('users/', users, name="users"),
    path('book-download-users/', book_download_users, name="book-download-users"),

    path('order/<status>', orders, name="orders"),
    path('update/order/', dnd_orders, name="order-status"),
    path('details/order-cart/', cart_detail_view, name="cart-detail"),


    path('list/products/', view_products, name="products"),
    path('add/products/', add_products, name="add-products")

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.contrib.auth import authenticate, login as auth_login,logout as auth_logout
from django.contrib.auth.decorators import login_required


from ecommerce.models import (   user_information,
                        product_category,
                        product_table,
                        cart_table,
                        cart_items,
                        shipping_information,
                        user_other_book_details,
                        order_table
                    )


# Create your views here.

def login(request):
    if request.method == 'POST':
        _username   = request.POST.get('username')
        _password = request.POST.get('password')
        user = authenticate(username=_username, password=_password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect("/dashboard")
            else:
                return render(request,'dashboard/login.html',{"success":False})
        else:
            return render(request,'dashboard/login.html',{"success":False})
    return render(request,'dashboard/login.html')


@login_required(login_url = 'dashboard:login')
def logout(request):
    auth_logout(request)
    return render(request,'dashboard/login.html')


@login_required(login_url = 'dashboard:login')
def analytics(request):
    order_inst = order_table.objects.filter(has_paid=True)
    total_amount = 0
    user_inst = user_information.objects.all()
    prod_inst = product_table.objects.all()

    for i in order_inst:
        total_amount += i.cart.grand_total_price
    context={
        "total_orders":order_inst.count(),
        "total_order_amount":total_amount,
        "user_inst":user_inst.count(),
        "prod_inst":prod_inst.count()
    }
    return render(request,'dashboard/analytics.html',context)


@login_required(login_url = 'dashboard:login')
def users(request):
    user_inst = user_information.objects.all()
    context={
        "user_inst":user_inst
    }
    return render(request,'dashboard/user-list.html',context)


@login_required(login_url = 'dashboard:login')
def book_download_users(request):
    user_inst = user_other_book_details.objects.all().order_by('-timestamp')
    context={
        "user_inst":user_inst
    }
    return render(request,'dashboard/book-download-user-list.html',context)


@login_required(login_url = 'dashboard:login')
def orders(request,status):
    if status=="delivered":
        order_inst = order_table.objects.filter(delivered=True).order_by("-order_date")
    else:
        order_inst = order_table.objects.filter(delivered=False).order_by("-order_date")
    context={
        "order_inst":order_inst
    }
    return render(request,'dashboard/order-list.html',context)


@login_required(login_url = 'dashboard:login')
def view_products(request):
    prod_inst = product_table.objects.all()
    context={
        "prod_inst":prod_inst
    }
    return render(request,'dashboard/product-list.html',context)


@login_required(login_url = 'dashboard:login')
def add_products(request):

    return render(request,'dashboard/product-add.html',context)


@login_required(login_url = 'dashboard:login')
def cart_detail_view(request):
    cart_id = request.POST.get('cart_id')
    cart_inst = cart_table.objects.get(id=cart_id)
    items = cart_inst.cart_items_set.all()
    ship_obj = order_table.objects.get(cart=cart_inst)
    cart_list={}
    items_list=[]
    for e,j in enumerate(items):
        if j.item.is_book:
            items_list.append({"name":j.item.name,"price":j.item.price,"type":"Book","quantity":j.quantity,"line_total":j.line_total})
        if j.item.is_ebook:
            items_list.append({"name":j.item.name,"price":j.item.price,"type":"E-book","quantity":j.quantity,"line_total":j.line_total})
        if j.item.is_other_item:
            items_list.append({"name":j.item.name,"price":j.item.price,"type":"Others","quantity":j.quantity,"line_total":j.line_total})

    cart_list['cart_det'] = items_list
    cart_list['total'] = cart_inst.grand_total_price
    cart_list['shipping_charges'] = cart_inst.shipping_price

    cart_list['address'] = {"street":ship_obj.shipping_address.street_address,"city":ship_obj.shipping_address.city,"state":ship_obj.shipping_address.state,"pincode":ship_obj.shipping_address.pincode}

    return JsonResponse(cart_list,safe=False)


@login_required(login_url = 'dashboard:login')
def dnd_orders(request):
    id = request.POST.get('id')
    status = request.POST.get('status')
    if status == "delivered":
        order_table.objects.filter(id=id).update(delivered=False)
        return JsonResponse({"result":"Deactivated"})
    else:
        order_table.objects.filter(id=id).update(delivered=True)
        return JsonResponse({"result":"Activated"})

dashboard/templates/dashboard/base-dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>AFHD-USA | Dashboard</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="{% static 'dashboard/css/sb-admin-2.min.css' %}" rel="stylesheet">

  <link href="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

<style>
  form.user .form-control-user{
      border-radius:0;
  }
  {% block css %}
  {% endblock %}
  </style>


</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">AFHD-USA</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="/dashboard">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:users' %}">
          <i class="fas fa-fw fa-shopping-bag"></i>
          <span>Users</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:book-download-users' %}">
          <i class="fas fa-fw fa-shopping-bag"></i>
          <span>Book Download Users</span></a>
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Products
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <i class="fas fa-fw fa-book"></i>
          <span>Products</span>
        </a>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'dashboard:products' %}">View all</a>
            <!-- <a class="collapse-item" href="{% url 'dashboard:add-products' %}">Add Items</a> -->
            </div>
          </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">


      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-user-circle"></i>
          <span>Orders</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'dashboard:orders' status='delivered' %}">Delivered</a>
            <a class="collapse-item" href="{% url 'dashboard:orders' status='undelivered' %}">Un-Delivered</a>
            </div>
          </div>
      </li>


      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:logout' %}">
          <i class="fas fa-window-maximize"></i>
          <span>Logout</span></a>
      </li>

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fas fa-window-maximize"></i>
          <span>Visit Website</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->

        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
          </div>



{% block content %}

{% endblock %}



        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; AFHD-USA</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'dashboard/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'dashboard/js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <!-- <script src="{% static 'dashboard/vendor/chart.js/Chart.min.js' %}"></script> -->

  <!-- Page level custom scripts -->
  <!-- <script src="{% static 'dashboard/js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'dashboard/js/demo/chart-pie-demo.js' %}"></script> -->



{% block tail %}

{% endblock %}

</body>

</html>

dashboard/templates/dashboard/order-list.html
{% extends "dashboard/base-dashboard.html" %}
{% load static %}

{% block css %}
  th,td{
    font-size:0.8rem;
  }
{% endblock %}


{% block content %}


  <!-- Modal -->
  <div class="modal fade" id="cartModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cart Summary</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <table class="table table-bordered cart-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Type</th>

                <th>Price</th>
                <th>Qty.</th>
                <th>Total Price</th>
              </tr>
            </thead>
            <tbody class='cart-body'>

            </tbody>
          </table>

          <h5>Shipping Address</h5>
          <table class="table table-bordered cart-ship-table">
            <thead>
              <tr>
                <th>Street Address</th>
                  <th>City</th>
                <th>State</th>
                <th>Pincode</th>
              </tr>
            </thead>
            <tbody class='ship-body'>

            </tbody>
          </table>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" onclick="printDiv();">Print</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="shipmentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Shipment Summary</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="table-responsive">
          <table class="table table-bordered shipment-table">
            <tbody class='shipment-body'>

            </tbody>
          </table>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
        </div>
      </div>
    </div>
  </div>


  <!-- Content Row -->
  <div class="row">

    <!-- Content Column -->
    <div class="col-lg-12 mb-4">

      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Orders list</h6>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered orders" width="100%" cellspacing="0" >
              <thead>
                <tr>
                  <th >#</th>
                  <th>Order Id</th>
                  <th>Stripe Id</th>
                    <th>Order Date</th>
                    <th>User Email</th>
                    <th>User name</th>
                  <th>User phone</th>

                  <th>Amount</th>
                  <th>Cart Detail </th>

                  <th>Delivery Detail </th>

                </tr>
              </thead>
              <tbody>

                {% for obj in order_inst%}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{obj.order_id}}</td>
                  <td>{{obj.stripe_payment_intent}}</td>
                  <!-- <td>{{obj.receipt_id}}</td> -->

                  <td>{{obj.order_date}}</td>

                  <td>{{obj.user.email}}</td>
                  <td>{{obj.user.name}}</td>
                  <td>{{obj.user.phone}}</td>


                  <td>{{obj.cart.grand_total_price}}</td>
                  <td>    <!-- Button trigger modal -->
                      <button type="button" class="btn btn-primary btn-sm show-cart" id={{obj.cart.id}} >
                        View Cart
                      </button>
                    </td>
                    {% if obj.delivered %}
                    <td><button class="btn btn-info btn-sm order_status{{obj.id}}" id="{{obj.id}}" onclick="myFunction(this);" value="delivered">Delivered</button></td>
                    {% else %}
                    <td><button class="btn btn-info btn-danger btn-sm order_status{{obj.id}}" id="{{obj.id}}" onclick="myFunction(this);" value="un-delivered">Un-Delivered</button></td>
                    {% endif %}
                </tr>
                {% endfor %}

              </tbody>
            </table>

          </div>
        </div>
      </div>

    </div>
  </div>

{% endblock %}

{% block tail %}

<!-- Page level plugins -->
<script src="{% static 'dashboard/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'dashboard/js/demo/datatables-demo.js' %}"></script>


<script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>


<script type="text/javascript">
  $(document).ready(function() {
    $('table.orders').DataTable(
        {
          dom:
        "<'row'<'col-sm-3'l><'col-sm-6 text-center'B><'col-sm-3'f>>" +
        "<'row'<'col-sm-12'tr>>" +
        "<'row'<'col-sm-5'i><'col-sm-7'p>>",
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ],
        }
        );

     $(".buttons-html5").addClass("btn-primary");
     $(".buttons-print").addClass("btn-primary");

} );
</script>

<script>
$(document).ready(function(){
  $(".show-cart").click(function() {
    cart_id = this.id,
    $.ajax({
      type: 'POST',
      url: "{% url 'dashboard:cart-detail' %}",
      data: {
        'cart_id': cart_id ,'csrfmiddlewaretoken': '{{ csrf_token }}'
      },
      dataType: 'json',

      success: function (data,textStatus) {

        $(".cart-body").html("");
        $(".ship-body").html("");
        for (var i=0;i<(data['cart_det'].length);i++){
          $(".cart-body").append
          (
          `<tr class='cart-product'>
            <th scope="row">`+(i+1)+`</th>
            <td>`+data['cart_det'][i]['name']+`</td>
            <td>`+data['cart_det'][i]['type']+`</td>

            <td>`+data['cart_det'][i]['price']+`</td>
            <td>`+data['cart_det'][i]['quantity']+`</td>
            <td>`+data['cart_det'][i]['line_total']+`</td>
          </tr>`
          )
        }
        $(".cart-body").append
        (
        `<tr>
          <td colspan="2"></td>
          <td style="text-align:right"><b>Shipping charge</b></td>
          <td>`+data['shipping_charges']+`</td>
        </tr>
        <tr>
          <td colspan="2"></td>
          <td style="text-align:right"><b>Total</b></td>
          <td>`+data['total']+`</td>
        </tr>`
      )

      $(".ship-body").append
      (
      `<tr class='cart-address'>
        <td>`+data['address']['street']+`</td>
          <td>`+data['address']['city']+`</td>
        <td>`+data['address']['state']+`</td>
        <td>`+data['address']['pincode']+`</td>
      </tr>`
      )

       $('#cartModal').modal('show')
      }
    })
  })
})

</script>

<script>
  function myFunction(objectact){
    var inputTitle = objectact.value
  // var x = document.getElementById("activebutton");
    var id = objectact.id

  if(inputTitle == "delivered"){
    status = 'True'
  } else {
    status = 'False'
}
  $.ajax({
    type: 'POST',
    url: "{% url 'dashboard:order-status' %}",
    data: {
      'id': id,'status':status ,'csrfmiddlewaretoken': '{{ csrf_token }}'
    },
    dataType: 'json',

    success: function (data,textStatus) {
      if (data['result'] == "Deactivated"){
            objectact.value = "un-delivered";
            $('.order_status'+id).html("Un-Delivered");
            $('.order_status'+id).addClass('btn-danger');
      }
      else{
        // $('#'+id).addClass('btn-damger')
        $('.order_status'+id).removeClass('btn-danger')
        objectact.value = "delivered";
        $('.order_status'+id).html("Delivered");
      }
    }
  })


}
  </script>
  <script>
         function printDiv() {
             var divContents = document.getElementById("cartModal").innerHTML;
             var a = window.open('', '', 'height=500, width=500');
             a.document.write('<html><head>');
             a.document.write(document.head.innerHTML);
             a.document.write('</head><body> <h1>Label</h1> <br>');
             a.document.write(divContents);
             a.document.write('</body></html>');
             a.document.close();
             a.print();
         }
     </script>
{% endblock %}